---
deployment:
  tasks:
    - export DEPLOYPATH=/home/rcarc/public_html/

    # Write a marker file so we KNOW deploy works
    - echo "Deployed at $(date)" > $DEPLOYPATH/deploy-log.txt

    # Sync everything from the repo to the live site
    - /bin/rsync -av --delete \
        --exclude=".git" \
        --exclude=".cpanel.yml" \
        ./ $DEPLOYPATH
