---
deployment:
  tasks:
    - export DEPLOYPATH=/home/rcarc/public_html/

    # Marker so we know this .cpanel.yml ran
    - echo "Deployed at $(date)" > $DEPLOYPATH/deploy-log.txt

    # DEBUG: list repo contents
    - pwd
    - ls -la

    # DEBUG: show contact.html in repo if it exists
    - ls -la contact.html || echo "contact.html not found in repo root"

    # Do the sync
    - /bin/rsync -avc --delete \
        --exclude=".git" \
        --exclude=".cpanel.yml" \
        ./ $DEPLOYPATH
