---
deployment:
  tasks:
    # Live site path
    - export DEPLOYPATH=/home/rcarc/public_html/

    # Marker so we know deploy ran
    - echo "Deployed at $(date)" > $DEPLOYPATH/deploy-log.txt

    # WARNING: wipe the existing site contents
    - find "$DEPLOYPATH" -mindepth 1 -maxdepth 1 -exec rm -rf {} \;

    # Copy everything from the repo into public_html
    - cp -R . "$DEPLOYPATH"

    # Clean up stuff we don't want live
    - rm -rf "$DEPLOYPATH/.git"
    - rm -f "$DEPLOYPATH/.cpanel.yml"
